using System;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Entities.Migrations
{
    /// <inheritdoc />
    public partial class AddHireRequestsAndUpdates : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"
CREATE TABLE IF NOT EXISTS ""HireRequests"" (
    ""HireRequestId"" integer GENERATED BY DEFAULT AS IDENTITY,
    ""RequestedBy"" character varying(20) NOT NULL,
    ""ProjectId"" integer,
    ""ProjectName"" character varying(200) NOT NULL,
    ""RoleNeeded"" character varying(120) NOT NULL,
    ""Quantity"" integer NOT NULL,
    ""StartDate"" timestamp with time zone NOT NULL,
    ""EndDate"" timestamp with time zone NOT NULL,
    ""Notes"" character varying(1000) NOT NULL,
    ""Status"" character varying(20) NOT NULL DEFAULT 'Open',
    ""HiredEmployeeName"" character varying(120),
    ""FulfilledBy"" character varying(20),
    ""FulfilledAt"" timestamp with time zone,
    ""CreatedAt"" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ""UpdatedAt"" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ""CreatedBy"" text NOT NULL,
    ""UpdatedBy"" text NOT NULL,
    CONSTRAINT ""PK_HireRequests"" PRIMARY KEY (""HireRequestId"")
);");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "HireRequests");
        }
    }
}
